# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 19:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=25)),
                ('Lname', models.CharField(max_length=25)),
                ('Nickname', models.CharField(max_length=25)),
                ('Techlevel', models.DecimalField(decimal_places=0, max_digits=1)),
                ('Year', models.DecimalField(decimal_places=0, max_digits=2)),
                ('Rating', models.DecimalField(decimal_places=0, max_digits=1)),
                ('Bio', models.TextField(max_length=300)),
                ('Genre', models.TextField(max_length=300)),
                ('Instruments', models.TextField(max_length=300)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
