# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='Address',
            field=models.TextField(default='HELLO', max_length=300),
            preserve_default=False,
        ),
    ]
