# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Fname', models.CharField(max_length=25)),
                ('Lname', models.CharField(max_length=25)),
                ('Nickname', models.CharField(max_length=25)),
                ('Techlevel', models.CharField(choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5')], default=b'1', max_length=1)),
                ('Year', models.CharField(max_length=2)),
                ('Rating', models.CharField(max_length=1)),
                ('Bio', models.TextField(max_length=300)),
            ],
        ),
    ]
