# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iter', '0002_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Genre',
            field=models.TextField(default=b'Electric', max_length=300),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Instruments',
            field=models.TextField(default=b'Drums', max_length=300),
        ),
    ]
