# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iter', '0003_auto_20161125_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.CharField(max_length=200)),
                ('Instruments', models.CharField(max_length=200)),
            ],
        ),
    ]
