# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iter', '0004_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connnections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User1', models.CharField(max_length=50)),
                ('User2', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='search',
            name='Instruments',
            field=models.CharField(choices=[(b'None', b'None'), (b'Drums', b'Drums'), (b'Guitar', b'Guitar')], default=b'None', max_length=200),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
