# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iter', '0005_auto_20161127_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User1', models.CharField(max_length=50)),
                ('User2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iter.Userdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='Connnections',
        ),
    ]
