# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iter', '0007_auto_20161127_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Rating',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Year',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
